# Disable rules from the default enabled set.
disabled_rules:
  - superfluous_disable_command
  - line_length
  - file_length
  - identifier_name
  - type_name
  - trailing_whitespace
  - function_body_length
  - operator_whitespace
  - redundant_optional_initialization
  - type_body_length
  - duplicate_enum_cases
  - nesting
  - function_parameter_count
  - cyclomatic_complexity
  - void_function_in_ternary
  - syntactic_sugar
  - unused_optional_binding
  - multiple_closures_with_trailing_closure

# Enable rules not from the default set.
opt_in_rules:

# Paths to include during linting.
included:

# Paths to ignore during linting.
excluded:

reporter: "xcode"
