swift_tool_version: 5.8
demo:
  ios_version: 15.7
  display_version: 1.0.0
  build_number: 1
  bundleIdentifier: com.chaltteok-studio.demo
  teamIdentifier: 6VSLC69397
  additional_info_plist_content_file_path: Support/Info.plist