// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NoticeDemo",
    platforms: [
        .iOS("15.7")
    ],
    products: [
        .iOSApplication(
            name: "The Code(Notice)",
            targets: ["NoticeDemo"],
            bundleIdentifier: "com.chaltteok-studio.notice-demo",
            teamIdentifier: "6VSLC69397",
            displayVersion: "1.0.0",
            bundleVersion: "1",
            appIcon: .asset("app_icon"),
            accentColor: .asset("accent_color"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "Support/Info.plist"
        )
    ],
    dependencies: [
        .package(path: "../../Package/Feature/Notice")
    ],
    targets: [
        .executableTarget(
            name: "NoticeDemo",
            dependencies: [
                "Notice"
            ],
            path: ".",
            linkerSettings: [
                .unsafeFlags([
                    "-ObjC"
                ])
            ]
        )
    ]
)
