// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SettingDemo",
    platforms: [
        .iOS("15.7")
    ],
    products: [
        .iOSApplication(
            name: "The Code(Setting)",
            targets: ["SettingDemo"],
            bundleIdentifier: "com.chaltteok-studio.demo",
            teamIdentifier: "6VSLC69397",
            displayVersion: "1.0.0",
            bundleVersion: "1",
            appIcon: .asset("app_icon"),
            accentColor: .asset("accent_color"),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            additionalInfoPlistContentFilePath: "Support/Info.plist"
        )
    ],
    dependencies: [
        .package(path: "../../Package/Feature/Setting")
    ],
    targets: [
        .executableTarget(
            name: "SettingDemo",
            dependencies: [
                "Setting"
            ],
            path: ".",
            linkerSettings: [
                .unsafeFlags(["-ObjC"])
            ]
        )
    ]
)
